version: '3.7'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USERNAME=postgres
    
  server:
    build: ./SpringPostgres
    depends_on:
      - database  
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 9000:9000
